services:
    front:
        image: ghcr.io/infcdaal1/rr-vue:dev
        container_name: front-local
        restart: unless-stopped
        ports:
            - "3000:80"
        depends_on:
            api:
                required: true
                condition: service_healthy
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api-local
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            DB_HOST: db
            DB_PORT: '${DB_PORT}'
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
        env_file:
            - .env
        volumes:
            - .:/app
        working_dir: /app
        depends_on:
            db:
                required: true
                condition: service_healthy
        networks:
            - db
        healthcheck:
            test: [ "CMD-SHELL", "curl -f http://localhost:8080/healty || exit 1" ]
            interval: 10s
            timeout: 5s
            retries: 5

    db:
        image: 'mariadb:11'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '0.0.0.0'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mariadb:/var/lib/mysql'
        networks:
            - db
volumes:
    mariadb:
        driver: local

networks:
    db:
        name: db  # Nom du réseau de base de données pour la communication entre les services
    traefik:
        name: traefik  # Nom du réseau Traefik pour la communication entre les services
