services:
    front:
        image: ghcr.io/infcdaal1/rr-vue:dev
        container_name: front-local
        depends_on:
            api:
                required: true
                condition: service_healthy
    api:
        build:
            context: .
            dockerfile: Dockerfile
            no_cache: true
            pull: true

        container_name: api-local
        ports:
            - "8080:80"
        environment:
            DB_HOST: db
            DB_PORT: '${DB_PORT}'
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        depends_on:
            db:
                required: true
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL", "curl -f http://localhost:80/up || exit 1" ]
            interval: 10s
            timeout: 5s
            retries: 15

    db:
        image: 'mariadb:11'
        ports:
            -   "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '0.0.0.0'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mariadb:/var/lib/mysql'
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
            start_period: 1m
            start_interval: 10s
            interval: 1m
            timeout: 5s
            retries: 3
volumes:
    mariadb:
        driver: local
