services:
  rr-front-prod:
    image: ghcr.io/infcdaal1/rr-vue:latest
    container_name: rr-front-prod
    restart: unless-stopped
    labels:
      - "traefik.enable=true"  # Activer Traefik pour ce service
      - "traefik.http.routers.rr-front-prod.rule=Host(`rr.qalpuch.cc`)"  # Règle de routage pour le service front
      - "traefik.http.routers.rr-front-prod.entrypoints=websecure"  # Utiliser le point d'entrée HTTPS
      - "traefik.http.routers.rr-front-prod.tls.certresolver=cloudflare"  # Utiliser le résolveur de certificats Cloudflare
      - "traefik.http.services.rr-front-prod.loadbalancer.server.port=80"
    depends_on:
      rr-api-prod:
        required: true
        condition: service_healthy
    networks:
      - traefik  # Utiliser le réseau Traefik pour la communication entre les services

  rr-api-prod:
    image: ghcr.io/infcdaal1/rr:latest
    container_name: rr-api-prod
    restart: unless-stopped
    labels:
    - "traefik.enable=true"  # Activer Traefik pour ce service
    - "traefik.http.routers.rr-api-prod.rule=Host(`rr-api.qalpuch.cc`)"  # Règle de routage pour le service API
    - "traefik.http.routers.rr-api-prod.entrypoints=websecure"  # Utiliser le point d'entrée HTTPS
    - "traefik.http.routers.rr-api-prod.tls.certresolver=cloudflare"  # Utiliser le résolveur de certificats Cloudflare
    - "traefik.http.services.rr-api-prod.loadbalancer.server.port=80"
    - "traefik.docker.network=traefik"  # Spécifier le réseau Traefik pour ce service
    environment:
      DB_HOST: rr-db-prod
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    env_file:
      - .env.prod
    depends_on:
      rr-db-prod:
        required: true
        condition: service_healthy
    networks:
      - traefik  # Utiliser le réseau Traefik pour la communication entre les services
      - rr-db-prod # Utiliser le réseau de la base de données pour la communication
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80/up || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 15

  rr-db-prod:
    image: 'mariadb:11'
    container_name: rr-db-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: '0.0.0.0'
      MYSQL_PORT: '${DB_PORT}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'rr_db_prod:/var/lib/mysql'
    networks:
      - rr-db-prod
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
volumes:
  rr_db_prod:
    driver: local

networks:
  rr-db-prod:
    name: rr-db-prod
  traefik:
    external: true
