#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# Vérification du dossier vendor
if [ ! -d ./vendor ]; then
    echo "Le dossier 'vendor' n'existe pas. Exécution de 'composer install'..."
    composer install
fi

# Vérification du dossier node_module
if [ ! -d ./node_module ]; then
    echo "Le dossier 'node_module' n'existe pas. Exécution de 'npm install'..."
    npm install
fi

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
