name: Laravel CI

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:11
        env:
          MYSQL_DATABASE: testing
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testing
      DB_USERNAME: root
      DB_PASSWORD:
      APP_ENV: testing
      APP_KEY: base64:ctJ9T+sHPspSesV/J894OBCT18tyaRphhfMEZ8NJ6og=
      APP_DEBUG: true
      BCRYPT_ROUNDS: 4
      CACHE_STORE: array
      MAIL_MAILER: array
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: array
      TELESCOPE_ENABLED: false
      JWT_SECRET: testing_secret_key_for_jwt

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: pdo_mysql,mbstring,xml,bcmath,intl,zip,gd,curl
        coverage: xdebug

#    - name: Setup Node.js
#      uses: actions/setup-node@v4
#      with:
#        node-version: '22'
#        cache: 'npm'

    - name: Copy .env
      run: cp .env.testing .env

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache/files
        key: dependencies-composer-${{ hashFiles('composer.json') }}

    - name: Install PHP Dependencies
      run: composer install --prefer-dist --optimize-autoloader

#    - name: Install Node Dependencies
#      run: npm ci
#
#    - name: Build frontend assets
#      run: npm run build

    - name: Generate App Key
      run: php artisan key:generate

    - name: Wait for Database
      run: |
        echo "Waiting for MariaDB to be ready..."
        for i in {1..30}; do
          nc -z 127.0.0.1 3306 && echo "DB is up!" && break
          echo "Waiting..."
          sleep 2
        done

    - name: Run Migrations and Seed
      run: |
        php artisan migrate --no-interaction --force
        php artisan db:seed --class=TestDatabaseSeeder --no-interaction --force

    - name: Run PHP Unit Tests
      run: composer test --coverage-clover coverage.xml

#    - name: Run PHP CS Fixer (Code Style)
#      run: |
#        composer require friendsofphp/php-cs-fixer --dev
#        vendor/bin/php-cs-fixer fix --dry-run --diff --verbose
#
#    - name: Run PHPStan (Static Analysis)
#      run: |
#        composer require phpstan/phpstan --dev
#        vendor/bin/phpstan analyse --memory-limit=1G

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: backend
        name: backend-coverage

  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
        extensions: pdo_mysql,mbstring,xml,bcmath,intl,zip,gd,curl

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Run Security Check
      run: |
        composer require enlightn/security-checker --dev
        vendor/bin/security-checker security:check composer.lock

  build-docker:
    name: Build Docker Image
    needs: [test, security]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      NODE_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
      TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
      REGISTRY: ghcr.io
      IMAGE_NAME: infcdaal1/rr

    concurrency:
      group: build-docker-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          build-args: NODE_ENV=${{ env.NODE_ENV }}
          cache-from: type=gha


      - name: Image pushed successfully
        run: echo "✅ Image ${{ env.TAG }} pushed to ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
